### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by S1NC0S** [decentraland/l2-airdrop#1]
After a bunch of working txs we're constantly running into this Error now right after starting the Airdrop with `npm run send`:

```
An error occurred trying to send the meta transaction. Error: Internal Server Error
Error: Internal Server Error
    at Object.<anonymous> (/home/sincos/projects/l2-airdrop/node_modules/src/sendMetaTransaction.ts:88:13)
    at Generator.next (<anonymous>)
    at i (/home/sincos/projects/l2-airdrop/node_modules/decentraland-transactions/index.js:24:86)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {}
```

It has been like this for 2 days now and we can't find out what the issue is. A better error message would be appreciated

**Comment by drexample** [comment]
experiencing same error

**Comment by 2fd** [comment]
I'm closing this issue because meta-transactions are deprecated, and they were removed on the latest version
